allow full mic device name , as prefix is changing from plughw to hw,…
fewieden/pocketsphinx-continuous-node pull request #4
Opened 2019-03-14 14:05 UTC by sdetweil

… don't break old apps

2019-08-10 08:56 UTC, fewieden requested changes
Hi @sdetweil thanks for your addition to this project. Please apply the requested changes so i can merge your pull request.

Also there seems to be a merge conflict, please merge the current master branch into yours.

Thank you

2019-08-10 08:56 UTC, fewieden commented on index.js
> +    let mic=this.microphone;
```suggestion
    let mic = this.microphone;
```

2019-08-10 08:56 UTC, fewieden commented on index.js
> +    if (this.microphone.match(/^\d/))
Can you please add brackets to the if statement, I'm not a fan of this syntax.

2019-08-10 08:56 UTC, fewieden commented on index.js
> +      mic = 'plughw:'+this.microphone;
```suggestion
      mic = `plughw:${this.microphone}`;
```

2019-08-10 08:56 UTC, fewieden commented on index.js
> +      'modules/MMM-voice/${this.setId}.lm',
Please revert this change, this is a bug.

2019-08-10 11:50 UTC, sdetweil commented on index.js
> +      mic = 'plughw:'+this.microphone;
i don't see that in my branch
i see
```
     `modules/${this.setId}/${this.setId}.lm`,
```

2019-08-11 07:26 UTC, fewieden commented on index.js
> +      mic = `plughw:+${this.microphone}`;
```suggestion
      mic = `plughw:${this.microphone}`; 
```

2019-08-11 07:26 UTC, fewieden commented on index.js
> +    if (this.microphone.match(/^\d/))
In the default config in the repo the microphone is a number, here you assume it is a string. But then the code will fail due to `TypeError: microphone.match is not a function`. See https://jsfiddle.net/38nwxmqs/

2019-08-11 07:29 UTC, fewieden commented on index.js
> +    if (this.microphone.match(/^\d/))
I fixed it on your branch

2019-08-11 07:30 UTC, fewieden commented on index.js
> +      mic = `plughw:+${this.microphone}`;
Fixed it on your branch

2019-08-11 07:31 UTC, fewieden approved these changes

2019-08-11 07:31 UTC, merged